name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi pydantic pytest uvicorn httpx

    # 4️⃣ Run tests
    - name: Run pytest
      run: python -m pytest -v

    # 5️⃣ Optional: Deploy FastAPI (example)
    - name: Run FastAPI app
      run: |
        nohup uvicorn main:api --host 0.0.0.0 --port 8000 &
